# Deployment config for Identity Server deployment
[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"
disable_addressing = true

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.user]
type = "mysql"
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[database.user.pool_options]
validationQuery = "SELECT 1"
[realm_manager]
data_source = "WSO2USER_DB"

[database.identity_db]
type = "mysql"
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.identity_db.pool_options]
validationQuery = "SELECT 1"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[database.shared_db.pool_options]
validationQuery = "SELECT 1"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

[[datasource]]
id = "WSO2ConsentDS"
url = "jdbc:mysql://wso2is-mysql-db-service:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"
[datasource.pool_options]
validationQuery = "SELECT 1"
maxActive=50
maxWait = 60000 # wait in milliseconds
testOnBorrow = true
jmxEnabled = false
[authentication.consent]
data_source="jdbc/WSO2ConsentDS"

[cors]
allow_generic_http_requests = true
allow_any_origin = true
allowed_origins = ["http://$ref{server.hostname}", "https://$ref{server.hostname}"]
allow_subdomains = true
supported_methods = [
    "GET",
    "POST",
    "HEAD",
    "OPTIONS"
]
support_any_header = true
supported_headers = []
exposed_headers = []
supports_credentials = true
max_age = 3600
tag_requests = false

[carbon_health_check]
enable= true
[carbon_health_check.health_checker.data_source_health_checker.properties]
'monitored.datasources' = "jdbc/WSO2CarbonDB,jdbc/WSO2UM_DB,jdbc/SHARED_DB"

#x509 config
[custom_trasport.x509.properties]
protocols="HTTP/1.1"
port="8443"
maxThreads="200"
scheme="https"
secure=true
SSLEnabled=true
keystoreFile="/repository/resources/security/localcert.jks"
keystorePass="wso2carbon"
truststoreFile="/repository/resources/security/cacerts.jks"
truststorePass="wso2carbon"
bindOnInit=false
clientAuth="want"
ssl_protocol = "TLS"

[certificate_validation]
ocsp_validator_enabled="false"
crl_validator_enabled="false"

[authentication.authenticator.x509_certificate.parameters]
name ="x509CertificateAuthenticator"
enable=true
AuthenticationEndpoint="https://localhost:8443/x509-certificate-servlet"
username= "CN"
UsernameRegex='([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9_-]+)'

#SMTP email server configurations
[output_adapter.email]
from_address= "is.demo@wso2.com"
username= "admin"
password= "admin"
hostname= "mailserver"
port= 1025
enable_start_tls= true
enable_authentication= true

[recaptcha]
enabled = "true"
api_url = "https://www.google.com/recaptcha/api.js"
verify_url = "https://www.google.com/recaptcha/api/siteverify"
site_key="6LfoXQEVAAA"
secret_key="6LfoXQEVAAA"

#Enable access for sample
[[resource.access_control]]
context = "(.*)/sample-auth/(.*)"
secure = false
http_method = "all"

#Enable Email OTP config
[authentication.authenticator.email_otp]
name ="EmailOTP"
enable=true
[authentication.authenticator.email_otp.parameters]
EMAILOTPAuthenticationEndpointURL = "https://localhost:9443/emailotpauthenticationendpoint/emailotp.jsp"
EmailOTPAuthenticationEndpointErrorPage = "https://localhost:9443/emailotpauthenticationendpoint/emailotpError.jsp"
EmailAddressRequestPage = "https://localhost:9443/emailotpauthenticationendpoint/emailAddress.jsp"
usecase = "local"
secondaryUserstore = "primary"
EMAILOTPMandatory = false
sendOTPToFederatedEmailAttribute = false
federatedEmailAttributeKey = "email"
EmailOTPEnableByUserClaim = true
CaptureAndUpdateEmailAddress = true
showEmailAddressInUI = true
useEventHandlerBasedEmailSender = true

#Enable self registration
[event.default_listener.identity_mgt]
priority= "50"
enable = false
[event.default_listener.governance_identity_mgt]
priority= "95"
enable = true
[event.default_listener.governance_identity_store]
priority= "97"
enable = true
[identity_mgt.user_onboarding]
enable_email_verification = true 
lock_on_creation=true

#Enable access for sample apps
[admin_service.wsdl]
enable = true
