version: "3"
services:

  # Database
  wso2is-mysql-db-service:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wso2carbon
      MYSQL_PASSWORD: wso2carbon
    volumes:
      - ./configs/mysql/initdb:/docker-entrypoint-initdb.d
      - ./configs/mysql/my.cnf:/etc/mysql/my.cnf
      # Uncomment this line to save any IS changes to a volume
      # - mysql-datavolume:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5

  # Local Mailserver
  mailserver:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  # Identity Server
  identity-server:
    image: docker.wso2.com/wso2is:5.11.0.0 #5.11.0.0 is the latest 5.11 version alias
    user: "root"
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8443:8443"
    entrypoint:
      - "sh"
      - "-c"
      - |
          wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.1.0/wait-for | 
          sh -s -- wso2is-mysql-db-service:3306 --timeout=160 -- echo "db ready";

          # Pre-start commands:
          cp -f $${WORKING_DIRECTORY}/wso2-config-volume/repository/conf/tomcat/catalina-server.xml.j2 $${WSO2_SERVER_HOME}/repository/resources/conf/templates/repository/conf/tomcat/catalina-server.xml.j2;

          echo "starting IS";
          $${WORKING_DIRECTORY}/docker-entrypoint.sh;
    healthcheck:
      test: ["CMD", "curl", "-k", "-v", "https://localhost:9443/api/health-check/v1.0/health"]
      interval: 5s
      timeout: 120s
      start_period: 100s
    volumes:
      - ./configs/identity-server:/home/wso2carbon/wso2-config-volume/repository/conf/
      - ./configs/security:/home/wso2carbon/wso2-config-volume/repository/resources/security/
      - ./components/dropins:/home/wso2carbon/wso2-artifact-volume/repository/components/dropins/
      - ./components/plugins:/home/wso2carbon/wso2-artifact-volume/repository/components/plugins/
    depends_on:
      - wso2is-mysql-db-service
      - mailserver

volumes:
  # Persistant mysql data
  mysql-datavolume:
    driver: local
